packages_add:
  - vim-enhanced
  - make 
  - automake
  - gcc 
  - gcc-c++ 
  - kernel-devel
  - cmake
  - python3-devel
  - python3-libselinux
  - python2-devel
  - python2-libselinux
package_remove:
  
