---
# tasks file for ansible-role-vim
- name: check mandatory role variables have been defined
  assert:
    that: user is defined

- name: include distribution specific tasks
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "{{ ansible_distribution }}.yml"

- name: setup powerline fonts
  include: powerline-fonts-fedora.yml
  when: ansible_distribution == "Fedora"

- name: Remove any packages, we do not want to have installed
  package: name="{{item}}" state=absent
  with_items: "{{package_remove | default([]) }}"
- name: Install required vim packages
  package: name={{item}} state=present 
  with_items: "{{packages_add}}"

- block:
    - name: Install Vundle
      git: repo=https://github.com/gmarik/Vundle.vim.git dest={{home}}/.vim/bundle/Vundle.vim
    - block:
        - name: Create vimrc
          template: src=vimrc.j2 dest={{home}}/.vimrc backup=True
          register: vimrc_installed
        - name: Install Plugins
          command: vim +PluginInstall +qall
          when: "vimrc_installed is changed"
  become: true
  become_user: "{{user}}"
