- name: Install Powerline Font
  file: path={{home}}/.fonts state=directory
- name: Download PowerlineSymbols
  get_url: url="https://github.com/powerline/powerline/raw/develop/font/PowerlineSymbols.otf" dest={{home}}/.fonts/PowerlineSymbols.otf
  register: powerline_symbols_download
- name: Execute Font Cache
  command: fc-cache -vf {{home}}/.fonts
  when: "{{powerline_symbols_download | changed }}"
- name: Create fontconfig conf.d directory
  file: path={{home}}/.config/fontconfig/conf.d state=directory
- name: Download powerline symbols.conf
  get_url:
    url: "https://github.com/powerline/powerline/raw/develop/font/10-powerline-symbols.conf"
    dest: "{{home}}/.config/fontconfig/conf.d/10-powerline-symbols.conf"
